from reportlab.lib.pagesizes import A4
from reportlab.lib.units import cm
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, HRFlowable
from reportlab.lib.enums import TA_CENTER, TA_LEFT


GREEN_PRIMARY = colors.HexColor("#2d6a4f")
GREEN_LIGHT = colors.HexColor("#d8f3dc")
TEXT_COLOR = colors.HexColor("#1a1a1a")
GRAY_COLOR = colors.HexColor("#6c757d")


def _escape_xml(text: str) -> str:
    return (
        text.replace("&", "&amp;")
            .replace("<", "&lt;")
            .replace(">", "&gt;")
    )


def generate_pdf(
    plan_text: str,
    origin: str,
    destination: str,
    start_date: str,
    end_date: str,
    passengers: int,
    output_path: str,
) -> None:
    doc = SimpleDocTemplate(
        output_path,
        pagesize=A4,
        topMargin=2 * cm,
        bottomMargin=2 * cm,
        leftMargin=2 * cm,
        rightMargin=2 * cm,
    )

    style_title = ParagraphStyle(
        "Title",
        fontSize=28,
        textColor=GREEN_PRIMARY,
        alignment=TA_CENTER,
        fontName="Helvetica-Bold",
        spaceAfter=4,
    )
    style_subtitle = ParagraphStyle(
        "Subtitle",
        fontSize=14,
        textColor=TEXT_COLOR,
        alignment=TA_CENTER,
        fontName="Helvetica",
        spaceAfter=16,
    )
    style_trip_label = ParagraphStyle(
        "TripLabel",
        fontSize=11,
        textColor=GREEN_PRIMARY,
        fontName="Helvetica-Bold",
        spaceAfter=4,
    )
    style_trip_value = ParagraphStyle(
        "TripValue",
        fontSize=11,
        textColor=TEXT_COLOR,
        fontName="Helvetica",
        spaceAfter=4,
    )
    style_section_heading = ParagraphStyle(
        "SectionHeading",
        fontSize=13,
        textColor=GREEN_PRIMARY,
        fontName="Helvetica-Bold",
        spaceBefore=10,
        spaceAfter=4,
    )
    style_body = ParagraphStyle(
        "Body",
        fontSize=10,
        textColor=TEXT_COLOR,
        fontName="Helvetica",
        spaceAfter=3,
        leading=14,
    )
    style_bullet = ParagraphStyle(
        "Bullet",
        fontSize=10,
        textColor=TEXT_COLOR,
        fontName="Helvetica",
        spaceAfter=3,
        leading=14,
        leftIndent=12,
        bulletIndent=0,
    )
    style_plan_title = ParagraphStyle(
        "PlanTitle",
        fontSize=15,
        textColor=GREEN_PRIMARY,
        fontName="Helvetica-Bold",
        spaceBefore=12,
        spaceAfter=8,
    )
    style_footer = ParagraphStyle(
        "Footer",
        fontSize=8,
        textColor=GRAY_COLOR,
        alignment=TA_CENTER,
        fontName="Helvetica",
        spaceBefore=16,
    )

    story = []

    # Header
    story.append(Paragraph("EcoWings", style_title))
    story.append(Paragraph("AI Travel Planner", style_subtitle))
    story.append(HRFlowable(width="100%", thickness=2, color=GREEN_PRIMARY, spaceAfter=12))

    # Trip Details
    story.append(Paragraph("Route:", style_trip_label))
    story.append(Paragraph(f"{origin} &rarr; {destination}", style_trip_value))
    story.append(Paragraph("Dates:", style_trip_label))
    story.append(Paragraph(f"{start_date} &ndash; {end_date}", style_trip_value))
    story.append(Paragraph("Passengers:", style_trip_label))
    story.append(Paragraph(str(passengers), style_trip_value))
    story.append(HRFlowable(width="100%", thickness=1, color=GREEN_PRIMARY, spaceAfter=12))

    # Plan content title
    story.append(Paragraph("Your Travel Plan", style_plan_title))

    # Parse and render plan_text
    for line in plan_text.split("\n"):
        stripped = line.strip()

        if not stripped:
            story.append(Spacer(1, 4))
            continue

        if stripped.startswith("## ") or stripped.upper().startswith("DAY "):
            escaped = _escape_xml(stripped.lstrip("# "))
            story.append(Paragraph(escaped, style_section_heading))
        elif stripped.startswith("- ") or stripped.startswith("• "):
            content = stripped[2:] if stripped.startswith("- ") else stripped[2:]
            escaped = _escape_xml(content)
            story.append(Paragraph(f"• {escaped}", style_bullet))
        else:
            escaped = _escape_xml(stripped)
            story.append(Paragraph(escaped, style_body))

    # Footer
    story.append(HRFlowable(width="100%", thickness=1, color=GRAY_COLOR, spaceBefore=16, spaceAfter=8))
    story.append(Paragraph(
        "Generated by EcoWings AI Travel Planner | ecowings.com",
        style_footer,
    ))

    doc.build(story)
