import os
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import cm
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib import colors
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, HRFlowable,
    Table, TableStyle, KeepTogether,
)
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.platypus import PageBreak
from reportlab.lib.utils import ImageReader

# ---------------------------------------------------------------------------
# Fonts – Arial supports full Turkish/Unicode character set
# ---------------------------------------------------------------------------
FONTS_DIR = "C:/Windows/Fonts"

def _register_fonts():
    try:
        pdfmetrics.registerFont(TTFont("Arial", os.path.join(FONTS_DIR, "arial.ttf")))
        pdfmetrics.registerFont(TTFont("Arial-Bold", os.path.join(FONTS_DIR, "arialbd.ttf")))
        pdfmetrics.registerFont(TTFont("Arial-Italic", os.path.join(FONTS_DIR, "ariali.ttf")))
        pdfmetrics.registerFont(TTFont("Arial-BoldItalic", os.path.join(FONTS_DIR, "arialbi.ttf")))
        pdfmetrics.registerFontFamily(
            "Arial",
            normal="Arial",
            bold="Arial-Bold",
            italic="Arial-Italic",
            boldItalic="Arial-BoldItalic",
        )
        return "Arial", "Arial-Bold"
    except Exception:
        return "Helvetica", "Helvetica-Bold"


FONT_NORMAL, FONT_BOLD = _register_fonts()

# ---------------------------------------------------------------------------
# Colour palette
# ---------------------------------------------------------------------------
GREEN_DARK   = colors.HexColor("#1b4332")
GREEN_MID    = colors.HexColor("#2d6a4f")
GREEN_ACCENT = colors.HexColor("#40916c")
GREEN_LIGHT  = colors.HexColor("#d8f3dc")
GREEN_PALE   = colors.HexColor("#f0faf3")
GOLD         = colors.HexColor("#b7924a")
TEXT_DARK    = colors.HexColor("#1a1a1a")
TEXT_MID     = colors.HexColor("#374151")
TEXT_LIGHT   = colors.HexColor("#6b7280")
WHITE        = colors.white
RULE_COLOR   = colors.HexColor("#c7e8d4")

# ---------------------------------------------------------------------------
# Helper: escape XML special characters
# ---------------------------------------------------------------------------
def _escape(text: str) -> str:
    return (
        text.replace("&", "&amp;")
            .replace("<", "&lt;")
            .replace(">", "&gt;")
            .replace('"', "&quot;")
    )


# ---------------------------------------------------------------------------
# Page template: decorative header band + page number footer
# ---------------------------------------------------------------------------
PAGE_W, PAGE_H = A4
MARGIN = 2 * cm
CONTENT_W = PAGE_W - 2 * MARGIN


def _draw_page(canvas, doc):
    canvas.saveState()

    # Top decorative band
    band_h = 1.1 * cm
    canvas.setFillColor(GREEN_DARK)
    canvas.rect(0, PAGE_H - band_h, PAGE_W, band_h, fill=1, stroke=0)

    # Thin accent line under the band
    canvas.setFillColor(GOLD)
    canvas.rect(0, PAGE_H - band_h - 3, PAGE_W, 3, fill=1, stroke=0)

    # Brand name in top band
    canvas.setFillColor(WHITE)
    canvas.setFont(FONT_BOLD, 10)
    canvas.drawString(MARGIN, PAGE_H - band_h + 0.3 * cm, "EcoWings")

    canvas.setFont(FONT_NORMAL, 9)
    canvas.setFillColor(GREEN_LIGHT)
    right_x = PAGE_W - MARGIN
    canvas.drawRightString(right_x, PAGE_H - band_h + 0.3 * cm, "AI Travel Planner")

    # Bottom rule + page number
    canvas.setStrokeColor(RULE_COLOR)
    canvas.setLineWidth(0.5)
    canvas.line(MARGIN, 1.4 * cm, PAGE_W - MARGIN, 1.4 * cm)

    canvas.setFont(FONT_NORMAL, 8)
    canvas.setFillColor(TEXT_LIGHT)
    canvas.drawCentredString(PAGE_W / 2, 0.85 * cm, f"Page {doc.page}")
    canvas.drawString(MARGIN, 0.85 * cm, "ecowings.com")
    canvas.drawRightString(PAGE_W - MARGIN, 0.85 * cm, "Generated by EcoWings AI")

    canvas.restoreState()


# ---------------------------------------------------------------------------
# Paragraph styles
# ---------------------------------------------------------------------------
def _styles():
    base = dict(fontName=FONT_NORMAL, textColor=TEXT_DARK, leading=16)

    title = ParagraphStyle(
        "DocTitle",
        fontName=FONT_BOLD, fontSize=30,
        textColor=GREEN_DARK,
        alignment=TA_CENTER,
        spaceAfter=2, leading=34,
    )
    subtitle = ParagraphStyle(
        "DocSubtitle",
        fontName=FONT_NORMAL, fontSize=13,
        textColor=TEXT_LIGHT,
        alignment=TA_CENTER,
        spaceAfter=0, leading=18,
    )
    section_heading = ParagraphStyle(
        "SectionHeading",
        fontName=FONT_BOLD, fontSize=13,
        textColor=GREEN_MID,
        spaceBefore=16, spaceAfter=6,
        leading=18,
        borderPad=0,
    )
    day_heading = ParagraphStyle(
        "DayHeading",
        fontName=FONT_BOLD, fontSize=12,
        textColor=WHITE,
        spaceBefore=14, spaceAfter=6,
        leading=16,
    )
    body = ParagraphStyle(
        "Body",
        fontName=FONT_NORMAL, fontSize=10,
        textColor=TEXT_MID,
        spaceAfter=4, leading=16,
    )
    bullet = ParagraphStyle(
        "Bullet",
        fontName=FONT_NORMAL, fontSize=10,
        textColor=TEXT_MID,
        spaceAfter=3, leading=16,
        leftIndent=16,
    )
    label = ParagraphStyle(
        "Label",
        fontName=FONT_BOLD, fontSize=9,
        textColor=GREEN_MID,
        spaceAfter=2, leading=13,
        textTransform="uppercase",
    )
    value = ParagraphStyle(
        "Value",
        fontName=FONT_NORMAL, fontSize=11,
        textColor=TEXT_DARK,
        spaceAfter=0, leading=15,
    )
    plan_intro = ParagraphStyle(
        "PlanIntro",
        fontName=FONT_BOLD, fontSize=16,
        textColor=GREEN_DARK,
        spaceBefore=0, spaceAfter=12,
        leading=22,
    )
    return {
        "title": title, "subtitle": subtitle,
        "section_heading": section_heading, "day_heading": day_heading,
        "body": body, "bullet": bullet,
        "label": label, "value": value, "plan_intro": plan_intro,
    }


# ---------------------------------------------------------------------------
# Trip-details card (table)
# ---------------------------------------------------------------------------
def _trip_details_table(origin, destination, start_date, end_date, passengers, styles):
    def cell(label_text, value_text):
        return [
            Paragraph(_escape(label_text), styles["label"]),
            Paragraph(_escape(value_text), styles["value"]),
        ]

    data = [
        cell("Route", f"{origin}  →  {destination}"),
        cell("Departure", start_date),
        cell("Return", end_date),
        cell("Passengers", str(passengers)),
    ]

    # Two-column layout: pair rows side by side
    paired = []
    for i in range(0, len(data), 2):
        left = data[i]
        right = data[i + 1] if i + 1 < len(data) else ["", ""]
        paired.append([left[0], left[1], right[0], right[1]])

    col_w = CONTENT_W / 4
    t = Table(paired, colWidths=[col_w * 0.55, col_w * 0.95, col_w * 0.55, col_w * 0.95])
    t.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), GREEN_PALE),
        ("ROWBACKGROUND", (0, 0), (-1, -1), [GREEN_PALE, WHITE]),
        ("TOPPADDING",    (0, 0), (-1, -1), 10),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 10),
        ("LEFTPADDING",   (0, 0), (-1, -1), 14),
        ("RIGHTPADDING",  (0, 0), (-1, -1), 10),
        ("GRID", (0, 0), (-1, -1), 0.5, RULE_COLOR),
        ("ROUNDEDCORNERS", [6]),
        ("BOX", (0, 0), (-1, -1), 1, GREEN_MID),
    ]))
    return t


# ---------------------------------------------------------------------------
# Day-heading badge
# ---------------------------------------------------------------------------
def _day_badge(text: str, styles):
    """Returns a 1-cell table that looks like a coloured pill/badge."""
    t = Table([[Paragraph(_escape(text), styles["day_heading"])]],
              colWidths=[CONTENT_W])
    t.setStyle(TableStyle([
        ("BACKGROUND",    (0, 0), (-1, -1), GREEN_MID),
        ("TOPPADDING",    (0, 0), (-1, -1), 7),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 7),
        ("LEFTPADDING",   (0, 0), (-1, -1), 14),
        ("RIGHTPADDING",  (0, 0), (-1, -1), 14),
        ("ROUNDEDCORNERS", [4]),
    ]))
    return t


# ---------------------------------------------------------------------------
# Main generator
# ---------------------------------------------------------------------------
def generate_pdf(
    plan_text: str,
    origin: str,
    destination: str,
    start_date: str,
    end_date: str,
    passengers: int,
    output_path: str,
) -> None:
    doc = SimpleDocTemplate(
        output_path,
        pagesize=A4,
        topMargin=2.2 * cm,
        bottomMargin=2.2 * cm,
        leftMargin=MARGIN,
        rightMargin=MARGIN,
    )

    styles = _styles()
    story = []

    # ---- Cover block ---------------------------------------------------
    story.append(Spacer(1, 0.6 * cm))
    story.append(Paragraph("EcoWings", styles["title"]))
    story.append(Paragraph("Your Personalised Travel Itinerary", styles["subtitle"]))
    story.append(Spacer(1, 0.5 * cm))
    story.append(HRFlowable(
        width="100%", thickness=2, color=GOLD,
        spaceAfter=0.5 * cm,
    ))

    # ---- Trip details card ---------------------------------------------
    story.append(_trip_details_table(
        origin, destination, start_date, end_date, passengers, styles
    ))
    story.append(Spacer(1, 0.6 * cm))
    story.append(HRFlowable(width="100%", thickness=0.5, color=RULE_COLOR, spaceAfter=0.5 * cm))

    # ---- Plan heading --------------------------------------------------
    story.append(Paragraph("Travel Plan", styles["plan_intro"]))

    # ---- Parse plan text -----------------------------------------------
    _is_day = lambda s: (
        s.startswith("## ") or
        s.upper().startswith("DAY ") or
        (len(s) > 3 and s[:3].upper() == "GÜN")
    )

    block = []   # collect items for KeepTogether around day headings

    def _flush(story, block):
        if block:
            story.append(KeepTogether(block))
        return []

    for raw_line in plan_text.split("\n"):
        stripped = raw_line.strip()

        if not stripped:
            story.append(Spacer(1, 5))
            continue

        if _is_day(stripped):
            block = _flush(story, block)
            heading_text = stripped.lstrip("# ").strip()
            block.append(_day_badge(heading_text, styles))
            block.append(Spacer(1, 6))
            continue

        # Generic section heading (###, bold-like lines ending with :)
        if stripped.startswith("### ") or (stripped.endswith(":") and len(stripped) < 60 and not stripped.startswith("-")):
            text = stripped.lstrip("# ")
            block.append(Paragraph(_escape(text), styles["section_heading"]))
            continue

        # Bullet items
        if stripped.startswith("- ") or stripped.startswith("• ") or stripped.startswith("* "):
            content = stripped[2:]
            # bold **…** handling
            content = _escape(content)
            content = content.replace("**", "<b>", 1).replace("**", "</b>", 1) if "**" in content else content
            block.append(Paragraph(f"• {content}", styles["bullet"]))
            continue

        # Regular body
        escaped = _escape(stripped)
        # handle inline bold
        if "**" in escaped:
            escaped = escaped.replace("**", "<b>", 1).replace("**", "</b>", 1)
        block.append(Paragraph(escaped, styles["body"]))

    _flush(story, block)

    # ---- Footer divider (content, not page footer) ---------------------
    story.append(Spacer(1, 0.8 * cm))
    story.append(HRFlowable(width="100%", thickness=0.5, color=RULE_COLOR))
    story.append(Spacer(1, 0.25 * cm))

    note_style = ParagraphStyle(
        "Note",
        fontName=FONT_NORMAL, fontSize=8,
        textColor=TEXT_LIGHT,
        alignment=TA_CENTER, leading=12,
    )
    story.append(Paragraph(
        "This itinerary was generated by EcoWings AI. "
        "Prices and availability may vary – always verify with airlines and hotels.",
        note_style,
    ))

    doc.build(story, onFirstPage=_draw_page, onLaterPages=_draw_page)
